import json
from pathlib import Path

p=Path(__file__).parent
base=json.loads((p/'Kenesis-Owner-Led-50.json').read_text(encoding='utf-8'))['companies']
rows=[x for x in base if x['geography']=='Tamil Nadu — other']
overrides={
'Aasic Plastic':dict(person='B. Sidhic',role='Proprietor; email is general business inbox',classification='general_only',evidence='Official contact explicitly labels this general communication and quotation email. Proprietor has a separate named phone, not a separately assigned email.'),
'Ammarun Foundries':dict(person='N. Visvanathan',role='CEO; family partnership founder',classification='direct_verified',evidence='Official contact page explicitly pairs CEO N. Visvanathan with visvanathan@ammarun.com. Verification means published person-address association, not deliverability.',additional_contacts=[dict(person='V. Arunkumar',role='Partner',email='arunkumar@ammarun.com',classification='direct_verified'),dict(person='C. Senthil Kumar',role='COO',email='senthilkumar@ammarun.com',classification='direct_verified')]),
'Bright Castings / Bright Groups':dict(person='S. Balraj',role='Joint Managing Director; owner in government programme',classification='direct_verified',evidence='Official contact page Contact Person block explicitly pairs S. Balraj with balraj@brightcastings.in and brightcast@gmail.com. Brochure and BEE establish role; undated ownership record still needs reconfirmation.'),
'Anu Foods (Pappa Brand Appalam)':dict(person='V. Balasubramanian',role='Proprietor',classification='direct_verified',evidence='Official contact names Mr. Balasubramanian for whole spices/flours at the same published phone and address. Official email previously extracted as bala@anufoods.in; government directory corroborates this address but uses a different family member as head. Prefer official named product contact. Shared family access possible.',extra_sources=['https://www.anufoods.in/contact/','https://www.nmpb.nic.in/sites/default/files/Final%20Report%20-%20Trader%20-%20Exporter%20-%20Importer%20-%20Extractor%20Directory.pdf'],additional_contacts=[dict(person='Arun Bala',role='Appalam/papad business contact; proprietor family',email='arunbala@anufoods.org',classification='direct_verified'),dict(person='Arjun Bala',role='Ground spices/masala business contact; proprietor family',email='arjunbala@anufoods.org',classification='direct_verified')]),
'Babu Engineering Foundry':dict(email='babu@babuengg.com',person='Boopendra Babu',role='Owner per BEE programme; Babu is cookware co-founder',classification='direct_verified',evidence='BEE programme directly pairs Boopendra Babu with babu@babuengg.com and 9994702223 at the matching Kannampalayam factory. Company-owned Bhagya Cookware contact independently publishes this exact email. Government record undated; mailbox delivery untested.',extra_sources=['https://sidhiee.beeindia.gov.in/AboutUs/participatingmsme','https://bhagyacookware.com/contact-us/','https://bhagyacookware.com/about-us/']),
'MG Knit Garments':dict(person='P. Manimaran',role='Founder',classification='direct_verified',evidence='Official website identifies founder P. Manimaran and publishes the exact matching named business email alongside its general Gmail inbox. The site does not guarantee only the founder reads it.',extra_sources=['https://www.mgknitgarments.com/about','https://www.mgknitgarments.com/contact-9']),
'Sri Amutham Apparel':dict(person='K. S. Sadhanandan',role='Founder and MD; named inbox association not explicit',classification='association_uncertain',evidence='Official homepage publishes sadha@sriamutham.in; about page identifies founder/MD K. S. Sadhanandan. No explicit name-to-email contact block found. Similarity of Sadha to Sadhanandan alone is insufficient to call it a verified owner inbox.'),
'Best Heat Treatment Services':dict(person='R. Nagarajan',role='Founder/managing partner; current selected email is a plant inbox',classification='general_only',evidence='Current official contact publishes marketing@bestheattreatment.com; existing sqf inbox is unit-specific. A 2019 university industrial-visit email explicitly copies Nagarajan at a Gmail address, but its age requires phone confirmation before using as current owner contact. Related official group brochure repeats address with an extra .com typo; do not silently correct from that source.',extra_sources=['https://www.bestheattreatment.com/contact-us/','https://kahedu.edu.in/naac/dvv/C-1/upload/1.3.4.1/project%20and%20field%20visit%20merged.pdf','https://www.sanprecisionalloys.com/wp-content/uploads/2023/04/Company-Brocuhure.pdf'],additional_contacts=[dict(person='R. Nagarajan',role='Managing director in 2019 correspondence',email='nagarajanbest1989@gmail.com',classification='association_uncertain',caveat='Person association explicit in university publication; current use unverified. Historical business-use address; phone-first.'),dict(person='K. Ravikumar',role='Senior Manager, Process, in 2019 correspondence',email='ravikumar@bestheattreatment.com',classification='association_uncertain',caveat='Historical named operations contact. Reconfirm present role.'),dict(person='',role='Current company marketing inbox',email='marketing@bestheattreatment.com',classification='general_only')]),
'Centwin Textile Mills Private Limited':dict(person='P. Kumaraswamy',role='Managing Director; email general',classification='general_only',evidence='Official site identifies MD and publishes company inboxes. No public direct MD address verified. Exporter-directory Centwin/hosiery entries may refer to the separated group entities and were not substituted.'),
'Koral International / Koral Knitting Mills':dict(person='C. Viswanathan / Anoop Viswanathan',role='Founder/chairman / CEO; email general',classification='general_only',evidence='Official site names both leaders but labels koral@koral.in as Indian customers contact and exports@koral.in as international customers contact. No direct leader address found.'),
'RBK Apparels':dict(person='R. Bharath Kumar',role='Founder and CEO',classification='direct_verified',evidence='Official contact page explicitly places rbk@rbkapparels.com under CEO R. Bharath Kumar. It also repeats the address as company inbox, so it may be shared. This is a documented named route, not an inference from initials.',extra_sources=['https://rbkapparels.com/contact.php']),
'Sakthi Heat Treatment Industry':dict(person='K. Andamuthu',role='Partner; email general',classification='general_only',evidence='Official page names partner Andamuthu but contact page publishes several unassigned inboxes. senthil@sakthiheattreatment.com is public but no owner/partner role association was verified. Old site content warrants phone confirmation.',additional_contacts=[dict(person='Senthil (full identity unverified)',role='Unstated',email='senthil@sakthiheattreatment.com',classification='association_uncertain')]),
'T-Form Garments / YOUKAY Fashion':dict(person='Mohamed Eliyas',role='Founder/proprietor; email support',classification='general_only',evidence='Official about page names proprietor and labels support@youkayfashion.com customer support. No published direct owner email found.'),
'Sathyam Labels':dict(person='N. K. Palanisamy',role='Founder; email association unassigned',classification='general_only',evidence='Official site names founder but gives shri@sathyamlabels.com and sathyamlabels@gmail.com in general company contact block. Shri is not assigned to founder; no direct owner email verified.')
}
out=[]
for x in rows:
    o=dict(overrides[x['name']])
    extra=o.pop('extra_sources',[])
    y=dict(name=x['name'],email=x['email'],person='',role='',classification='general_only',source_urls=list(dict.fromkeys([s['url'] for s in x['sources']]+extra)),checked_date='2026-09-15',delivery_tested=False)
    y.update(o)
    out.append(y)
assert len(out)==14
(p/'owner_email_enrichment_tn.json').write_text(json.dumps(out,indent=2,ensure_ascii=False),encoding='utf-8')
print({c:sum(x['classification']==c for x in out) for c in ['direct_verified','general_only','association_uncertain']})
