import json
from pathlib import Path

p=Path(__file__).parent
rows=json.loads((p/'Kenesis-Owner-Led-50.json').read_text(encoding='utf-8'))['companies'][:13]
out=[]
for r in rows:
    out.append(dict(name=r['name'],email=r['email'],role=r['leadership'],person=r['leadership'].split(' — ')[0],classification='general_only',source_urls=[s['url'] for s in r['sources']],evidence='Official company mailbox retained. Targeted owner-name and company searches did not establish a separately published direct owner email.',checked_date='2026-09-15'))
d={r['name']:r for r in out}
d['Electron Coil Technology'].update(classification='direct_verified',person='R Umashankar',role='Proprietor',evidence='Official website names the proprietor. Government MSME April 2025 sanction order explicitly pairs UMASHANKAR with ectshankar@gmail.com and matching company address. Published business contact association verified; inbox delivery and exclusive ownership untested.',source_urls=['https://ecttransformers.com/','https://www.dcmsme.gov.in/CLCS_TUS_Scheme/PMS/s/Sanction-Order-date-11-04-2025.pdf'])
d['Guru Mangala Engineering'].update(classification='association_uncertain',person='V Sivanesan',role='Proprietor',evidence='Official contact block names proprietor V Sivanesan and lists vsiva_suma@yahoo.com plus gurumangalaengg@gmail.com. Mailbox is published and owner-associated, but the page does not explicitly assign either address to him individually.',source_urls=['https://www.gurumangalaengg.com/about-us/','https://www.gurumangalaengg.com/gallery/'])
d['Ambattur Metal Treaters'].update(email='amtheat.ns@gmail.com',classification='direct_verified',person='N Sampathkumar',role='CEO / proprietor',evidence='ASM India member directory individual record names N Sampathkumar and lists amtheat@hotmail.com / amtheat.ns@gmail.com, with CEO/proprietor role and matching factory contacts. Publication date is unclear. Personal business association verified; delivery untested.',alternate_emails=['amtheat@hotmail.com'],source_urls=['https://cdnc.heyzine.com/files/uploaded/v2/cba6aa8c84c81b1fadcc84a1a37de3e0dbe8b78f.pdf','https://www.amtheat.com/','https://asm-htse.com/htse-committee.php'])
d['Manav Packaging Private Limited'].update(classification='direct_verified',person='Dhinesh Kumar Varadharajan',role='Managing Director',evidence='Current official contact page republishes dhinesh@manavpackaging.in. EPCES 2019–20 annual report explicitly assigns this email to the named managing director. A 2025 council meeting record corroborates continuing MD role. Delivery untested.',source_urls=['https://www.manavpackaging.in/contact.php','https://www.epces.in/EPCES-Annual-Report-2019-20-final-draft-as-on-21-10-2020.pdf','https://www.seepz.gov.in/public/uploads/174239112467dac7541973d_EPCES.pdf'])
d['Best Cast IT Limited (Best Cast)'].update(evidence='Official leadership and contact pages retain sales@bestcastgroup.com. Corporate directories also expose balu@bcil.net and cs@shareway.in, neither demonstrated to belong to the owner. A related-company email mentioning Murali was not promoted to a verified factory-owner route.')
d['Perfect Controls'].update(person='M Krishnamurthy',role='Current proprietor / CEO',evidence='Official about and contact pages publish sales@perfectcontrols.com. Search found only masked purported individual emails in lead databases; no complete direct email verified.',source_urls=['https://www.perfectcontrols.com/about.html','https://perfectcontrols.com/contact.html'])
d['Thirumala Press Components Pvt Ltd (TPC)'].update(classification='association_uncertain',person='Suresh A G / Sharath Suresh',role='Chairman / Managing Director; major shareholders',candidate_email='suresh@tpcpltd.com',candidate_email_status='Published secondary corporate contact; individual assignment unconfirmed',evidence='Current official website publishes sales@tpcpltd.com and names Suresh A G and Sharath Suresh. Tofler publishes suresh@tpcpltd.com as company email, not explicitly chairman email. ClearTax has older suresh@thirumalapresscomponents.com. Retain official sales address until owner association is confirmed.',source_urls=['https://www.tpcpltd.com/about','https://www.tofler.in/thirumala-press-components-private-limited/company/U29130TN1992PTC022712','https://cleartax.in/f/company/thirumala-press-components-private-limited/U29130TN1992PTC022712/'])
d['Vicoplast Packing Industries Private Limited'].update(classification='association_uncertain',person='G Palani / Palani Gnanam',role='Founder / director',candidate_email='palanig@sriramforklifters.com',candidate_email_status='Published secondary corporate contact; individual assignment unconfirmed',evidence='Official company website publishes vicoplastindia@gmail.com and names founder G Palani. EasyLeadz and InsiderBiz publish palanig@sriramforklifters.com as corporate email and separately list director Palani Gnanam. Individual mailbox assignment and current use are not established. Retain official email as primary.',source_urls=['https://www.vicoplastindia.com/about-us/','https://www.easyleadz.com/company/vicoplast-packing-industries-private-limited-U25205TN2020PTC133935','https://www.insiderbiz.in/company/VICOPLAST-PACKING-INDUSTRIES-PRIVATE-LIMITED'])
d["Aphrodite's Drape"].update(source_urls=['https://www.aphroditesdrape.in/about-us/'],evidence='Current official about page names founder/proprietor Shanmugapriya and gives aphroditesdrape@gmail.com as company contact. No separately assigned personal business email found.')
assert len(out)==13
(p/'owner_email_enrichment_chennai_a.json').write_text(json.dumps(out,ensure_ascii=False,indent=2),encoding='utf-8')
print({c:sum(r['classification']==c for r in out) for c in ['direct_verified','general_only','association_uncertain']})
